#!/bin/bash

# main configs 
cleint_dir="dir1"
backup_dir="dir2"
user=""

# id args
while [ -n "$1" ]
do
case "$1" in
	-id) client_id="$2"
	esac
	shift
done


if [ $client_id ]
then
	client_dir="$client_dir/$client_id"
	backup_dir="$backup_dir/$client_id"

	if [ -d $cleint_dir ]
	then

		echo "Client dir exist $client_dir"
	else
		echo "Client dir dosen't exist $cleint_dir"


	if [ -d $backup_dir ]
	then
		echo "Backup dir exist $backup_dir"
		
		if [ ! -d $cleint_dir ]
				then
					mkdir $cleint_dir
				fi

		for file in $backup_dir/*
		do
			mv $file $cleint_dir
		done
		rmdir $backup_dir

		sudo chown $user:$user -R $dir2
		sudo chmod g+w -R $dir2
		echo "Recovery completed: cd $cleint_dir"		
	else
		echo "Backup dir dosen't exist $backup_dir"
	fi

else
	echo "-id didn't transfer"
fi
