#!/bin/bash

dir1="dir1"
dir2="dir2"
user=""

while [ -n "$1" ]
do
case "$1" in
	-id) client_id="$2"
	esac
	shift
done


if [ $client_id ]
then
	dir1="$dir1/$client_id"
	dir2="$dir2/$client_id"
	echo $dir1
	if [ -d $dir1 ]
	then

		echo "Dir exist $dir1"
		if [ ! -d $dir2 ]
		then
			mkdir $dir2
		fi

		for file in $dir1/*
		do
			mv $file $dir2
		done

		rmdir $dir1

		sudo chown $user:$user -R $dir2
		sudo chmod g+w -R $dir2
		echo "Recovery completed: cd $dir2"

	elif [ -d $dir2 ]
	then

		echo "Dir dosen't exist $dir1"
		echo "Exist $dir2"

	else

		echo "Dir dosen't exist $dir1"
		echo "Dir dosen't exist $dir2"

	fi
else
	echo "-id didn't transfer"
fi
